mysql:
  user: root
  password: Andy401927
  host: 127.0.0.1
  port: 3306
redis:
  host: 127.0.0.1
  port: 6379
  password: # 密码(可为空)
  defaultDB: 0 # 默认DB
  dialTimeout: 5s #redis连接超时时间.默认5s
elastic:
  url: http://127.0.0.1:9200 # 服务地址，多个地址用逗号隔开
  sniff: false # 是否转换请求地址，默认为true,当等于true时 请求http://ip:port/_nodes/http，将其返回的url作为请求路径